### PR TITLE
Centered bunch

### PR DESCRIPTION
**Pull request by arnaualba**
Refers to issue #18 
This is my proposition to center the bunch. If the mesh option `optimize-position = true` is set, then the bunch is shifted such that the bunch center will hit the undulator edge at z = 0.

Let me know if you agree with my implementation

### CODE REVIEW

**Comment by aryafallahi** [comment]
Dear Arnau,

I probably misunderstood you when you were proposing this, or I have a wrong impression from your implementation here. Note that if part of the bunch during initialization is located inside the undulator, the results will be completely wrong. The reason is that the electrons follow a certain trajectory in the undulator, meaning that the position and velocity induced by the undulator is obtained from the fields. If a particle is initialized inside the undulator with the given parameter in bunch initialization, then it will be considered that it has passed through the undulator without having the trajectory induced on the motion. This leads to wrong results. This is the reason that in mithra the optimum option is to have the head of the bunch at the undulator begin, so that all the particles are out of the undulator meanwhile unnecessary propagation of the particles are avoided.

If we initialize the bunch with its center at the beginning of the undulator not only it is not optimal but also the results will be wrong.

**Comment by arnaualba** [comment]
Thank you for the feedback Arya. 
I understand and I probably didn't explain myself well.
With this implementation the initial distance between the undulator and the bunch is not changed. 

The problem I want to solve is the following:
In the comoving frame, the bunch is moving forwards in the beginning of the simulation. Then when it enters the undulator it stops moving and stays in place during the whole simulation, until it exits the undulator at the end of the simulation. 
The problem is that when the bunch stops it might not be at z = 0. It could stop at z <<0 or z >> 0, and could in fact end up out of the computational domain.

That is why in this implementation I shift the bunch backwards **in the computational domain**, but the initial distance from the undulator remains unchanged. The shift is computed such that when the center of the bunch reaches the undulator begin, it will be at z = 0 in the computational domain. Therefore when the bunch stops moving it will be at z = 0, and it will be centered in the computational domain.

You can see this in the plots below (units are wrong, please ignore them). The two simulations are exactly the same. The only difference is the z-plot. As you can see the bunch with the "optimize-position" has mean position of z = 0 during most of the simulation so we are sure that it is entirely in the computational domain. The other bunch has z > 0, and might be out of the mesh. Even if the user chose a big mesh to fit in the bunch, the bunch might be on the edge or even out of it.

Do you agree?

avg

**Comment by aryafallahi** [comment]
Dear Arnau,

thanks for the detailed explanation.

I am just having a hard time to understand your solution. Because, I think what I have already implemented is optimal. The length of the bunch will be multiplied by gamma_ when it is in the undulator. The mesh size is slightly larger than the bunch size multiplied by gamma_. In the current implementation, the head of the bunch will immediately enter the undulator and remains unmoving there. So, if the head of the bunch is positioned at zmax*gamma then after entering the undulator the whole bunch should stay inside the mesh with optimal distribution.

But, I see you have done the nice test for your solution. would you please send me your job file so that I can also study it and dig out where I do not understand my mistake.

**Comment by arnaualba** [comment]
Hi Arya,

I mostly agree with what you are saying, but however there is one thing that I believe you have missed.
You say  "the head of the bunch will immediately enter the undulator", but this is not always true. The bunch head-to-undulator distance is chosen by the user, and by default it is 2 * lu. This distance might be very big, and this means that the bunch head might take a long time to enter the undulator, and hence might become unmoving at z >> 0.

[jobfiles.zip](https://github.com/aryafallahi/mithra/files/4528263/jobfiles.zip)

You can see the two jobfiles I have added. You will need to checkout the branch
```
git clone https://github.com/arnaualba/mithra.git
git checkout centeredBunch
```

The difference between the two jobfiles is not so obvious in this case, but if you increase the distance-to-bunch-head or the period you will see that the buch takes a longer time to enter the undulator, and becomes unmoving at z >> 0.

Let me know what you think.

**Comment by aryafallahi** [comment]
Good, and thanks for the clarification now I see what you exactly meant.

Just one last question. With this explanation, if the bunch head resides exactly at the head of the undulator, then we should not get any shift. However, your formulation still shifts the bunch. What is wrong with my assumption?

**Comment by arnaualba** [comment]
If in this case it didn't apply any shift the bunch would end up slightly to the right with avg(z) > 0. 
In the case that you mention the bunch head is unmoving from the start of the simulation and it is at zhead = gamma_ * zmax' .
When the bunch enters the undulator, its center-to-head distance in the computational domain is gamma_ * (zmax' * beta_0 / beta_z'), so a bit shorter than zhead. Thus the bunch center will end up at z > 0.

The shift makes sure that the bunch center ends up at z = 0

I hope my explanation makes sense. It's a bit hard to write down without complicated formulas.

**Comment by aryafallahi** [comment]
Great!, yes the explanation makes completely sense. I will merge this later in the weekend.

**Comment by arnaualba** [comment]
Great, thanks. No hurry for the merge

**Comment by arnaualba** [comment]
Hello Arya,
Could we get this last request merged, please? It's the last update I am waiting on. Then the OPAL-MITHRA mix will work better.

Thanks.

PS : if you don't agree with the implementation let me know and I can change it-

**Comment by aryafallahi** [comment]
oh sorry, I completely forgot it. too busy these days. I will do it now.

**Comment by arnaualba** [comment]
> oh sorry, I completely forgot it. too busy these days. I will do it now.

Thank you very much Arya, it's working great now :)

**Pull request merged**
