### PR TITLE
Total distance

### PR DESCRIPTION
**Pull request by arnaualba**
This is just a proposition, you don't have to merge it if you don't agree. When we discussed it you said that it would slow down the code to do it this way.
I have implemented and in a small test on my laptop I saw no significant slow down.
Let me know what you think.

Personally I like this implementation, and I think it also saves time because you only simulate up to the point you need. By giving a total time you might be simulating for too long, in which case the simulation takes longer than needed, or too little, in which case you only discover after the simulation that you had actually given a wrong time.

### CODE REVIEW

**Comment by arnaualba** [comment]
Refers to issue #26

**Comment by aryafallahi** [comment]
@arnau can you check your implementation on a big test. This is something that comes along in big simulations. For example, when you have 10 millions of particles and it passes through a long undulator. The question is what will be the difference in total simulation time when we check for this.

**Comment by arnau** [comment]
@aryafallahi you probably meant @arnaualba

**Comment by arnaualba** [comment]
> can you check your implementation on a big test. This is something that comes along in big simulations. For example, when you have 10 millions of particles and it passes through a long undulator. The question is what will be the difference in total simulation time when we check for this.

Ok yes I will do that. After I test it we can decide if we merge it or not. Thanks

**Comment by aryafallahi** [comment]
@arnaualba Sorry Arnau, I do not know what has happened to github, but I can not see my second comment. The above comment I wrote before I read your commits. After I studied, I think your commits are no different computationally from what was before. There is a problem with code readability. I personally try not to define functions for 2-3 code lines, so that the code is readable for others. Therefore, I think you do not need to test this implementation.

**Comment by arnaualba** [comment]
Hi @aryafallahi, 
Ok I understand, you don't have to merge it then if you don't agree. 
But I will try explain why I did it this way:

- Regarding the **small functions**, in my opinion every bit of code that is repeated in more than one place should be a function. This way it's easier to maintain and less prone to errors. The functions getZmin() and getZLab() are repeated in the code. If, for example, you decide to implement differently the transfomation to laboratory coordinates, you will only need to change the function, instead of several lines in the code. In my opinion the code becomes more readable, as long as the functions are well named. For example we could name it `trafoToLab()`:
`ubp.lz = trafoToLab(rnp[2]);` 
which I think is easier to understand than
`ubp.lz = gamma_ * (rnp[2] + c0_ * beta_ * (timeBunch_ - dt_))` 

- Regarding the **totalDistance**, the method that I implemented is not very time consuming, since the loop over all particles is only to find `zmin`. Once it has been found, only that particle needs to be checked if its lab position is larger than `totalDist_`.  I tested the example jobfile `FEL-IR-DT100.job`, which has 1e6 particles and 1e7 gridpoints, on 32 cores. In the following image you see the comparison between two output files. In the top output file I made it stop after the undulator at `total-distance = 9.1e6`, and printed out the total time that was simulated.
In the bottom file, I set `total-distance`to zero and gave `total-time =  32943.4`, such that it would simulate the exact same time interval. By comparing the  `total simulation time` you can see it only took 1% longer when the distance was being checked at each loop.

Screenshot from 2020-05-23 14-41-54

**Comment by aryafallahi** [comment]
Concerning the first point, I think it is more a matter of coding taste. I prefer to have functions defined only if it is necessary and the necessity criterion is very much person dependent.

Concerning the second point, there is a subtle thing we need to consider. With time new ideas come and new applications emerge. They usually need addition of new features to the code. If in each stage the best solution is not implemented the addition of such 1% cases become easily 5-10%. In a simulation that takes 5 days which are very typical, 10% is half a day. 1% is already an hour. So it is best that the features are always implemented such that no additional cost is on the code, always 0% if it is possible. The example you tested has almost equal computation cost for the bunch, field and radiation power. It means the check you have implemented has added 3% cost to the bunch part. This means that if you have a computation where bunch calculation is the dominant part and it takes a week for example, this 3% will be 2-3 hours. If such features are added 2-3 times you very fast see addition of a one more day simulation. Just consider that the emission-particle feature has already done the same cost addition to the bunch part.

**Comment by arnaualba** [comment]
Thanks for the feedback @aryafallahi , I understand your point. 
This feature is not strictly necessary and adds unnecessary computational costs.
I will close this request then.

**Pull request closed without merging**
